[versions]
accompanist = "0.32.0"
activityCompose = "1.9.2"
android-gradle = "8.11.1"
coil = "2.7.0"
composeBom = "2024.09.01"
composeCompiler = "1.5.8"
coreKtx = "1.13.1"
detekt = "1.23.5"
flexmark = "0.64.8"
immutableCollections = "0.4.0"
jvm = "17"
kodeview = "0.9.0"
kotlin = "2.2.0"
coreKtxVersion = "1.16.0"
m2ci = "64"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
flexmark = { module = "com.vladsch.flexmark:flexmark", version.ref = "flexmark" }
flexmark-autolink = { module = "com.vladsch.flexmark:flexmark-ext-autolink", version.ref = "flexmark" }
flexmark-gfm-strikethrough = { module = "com.vladsch.flexmark:flexmark-ext-gfm-strikethrough", version.ref = "flexmark" }
flexmark-gfm-tasklist = { module = "com.vladsch.flexmark:flexmark-ext-gfm-tasklist", version.ref = "flexmark" }
flexmark-superscript = { module = "com.vladsch.flexmark:flexmark-ext-superscript", version.ref = "flexmark" }
flexmark-tables = { module = "com.vladsch.flexmark:flexmark-ext-tables", version.ref = "flexmark" }
immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutableCollections" }
kodeview = { module = "dev.snipme:kodeview", version.ref = "kodeview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
m2ci = { id = "com.m2mobi.m2ci", version.ref = "m2ci" }

[bundles]
