name: 'Build'

on:
  push:
    branches:
      - '**develop'
      - 'release/**'
      - 'master'
  pull_request:

permissions:
  contents: write

jobs:
  pipeline:
    uses: move-android/ams-actions/.github/workflows/build.yml@master
    secrets:
      artifactory-url: ${{ vars.ARTIFACTORY_URL }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      debug-keystore: ${{ secrets.DEBUG_KEYSTORE }}
      release-keystore: ${{ secrets.RELEASE_KEYSTORE }}
      github-token: ${{ secrets.READ_GITHUB_PACKAGE_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      sonar-url: ${{ vars.SONAR_HOST_URL }}
      app-distribution-account: ${{ secrets.APP_DISTRIBUTION_ACCOUNT }}
      slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
      private-repo-ssh-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
    with:
      java-version: 17
      use-larger-runner: true
      setup-init-file: true
